### ISSUE TITLE
any hope for qt5/kf5 port?

### ISSUE THREAD

**Issue by ahjolinna** [sandsmark/Spokify#3]
it seems this project is dead (but I ask anyway), and it is really shame...at least now when spotify decided to go with (for linux) a pure gtk/web-app for their next release -_-'
so native kde experience would be really nice, also clementine tomahawks plugins are not that good

**Comment by akikoskinen** [comment]
Yes, dead would be a pretty accurate description of the state of this project. At least from my part. Currently.

That doesn't mean that it won't ever resurrect, however. Currently I don't have time to contribute to this project. But sometimes late at night I dream that I could find some time every once in a while.

Contributions are off course always welcome.

Edit: whoops, I thought this issue was in my fork of the project but then realized that's not the case. My comment is purely my own view of the situation.
